name: cd

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  npm:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 23
      - name: Install dependencies
        run: npm ci
      - name: Publish to npm
        if: secrets.NPM_TOKEN != ''
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
